stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the project web server in the background
    - npm run start:ci # &
    # run Cypress tests within the GitHub repository
    # npx cypress run --browser firefox 
    #npm run e2e
