name: Cypress Tests

on: [push]

jobs:
  test99:
    runs-on: ubuntu-latest
    name: check tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: testomatio/check-tests@stable
        with:
          framework: cypress.io
          tests: "./cypress/integration/**/**.spec.js"
          token: ${{ secrets.GITHUB_TOKEN }}
          has-tests-label: true
